config.yaml
data/costs.csv
scripts/prepare_sector_network.py

* prepare_sector_network:
- add link for oil boiler in function add_industry()
- add function for partitioning clusters into different heat node types
* config.yaml: add option for oil_boiler
* costs.csv: add costs for oil boiler

add new link oil boiler

---

doc/installation.rst

PyPSA-Eur datafiles are now part of the snakemake flow. Updated the instructions to prevent confusion.

Update installation notes

---

scripts/add_brownfield.py
scripts/add_existing_baseyear.py
scripts/build_biomass_potentials.py
scripts/build_industrial_demand.py
scripts/make_summary.py
scripts/plot_summary.py
scripts/prepare_sector_network.py
scripts/solve_network.py

change reading the config.yaml for testing from depreciated yaml.load() to yaml.safe_load()

read config.yaml for testing with yaml.safe_load()

---

config.default.yaml
config.myopic.yaml
scripts/prepare_sector_network.py

1. add missing resitive heater + micro CHP to electricity distribution
2. restrict solar rooftop potential to 10m² per person
3. add new electricity demand of industry to electricity distribution
4. add option to add costs for gas distribution, currently assuming same costs for gas distribution as for electricity distribution

Distribution

---

.gitignore
Snakefile
doc/data.csv
doc/installation.rst
doc/release_notes.rst
scripts/build_industrial_distribution_key.py
scripts/build_industrial_energy_demand_per_node.py
scripts/build_industrial_energy_demand_per_node_today.py
scripts/build_industrial_production_per_node.py
scripts/prepare_sector_network.py

I.e. per sector geographical distribution of industrial facilities within each country.
Drop facilities outside Europe and with no geocoordinates.
Use ETS emissions as a distribution key; where emissions data is missing, substitute with an average for that sector and that country (strong assumption).
This PR addresses https://github.com/PyPSA/pypsa-eur-sec/issues/16.

Use hotmaps industrial database for distribution of industry in each country

---

config.default.yaml
scripts/plot_summary.py
scripts/prepare_sector_network.py

- Move key parameters to config.yaml
- Use new DEA assumptions for post-capture on CHP, cement and other industrial sources
- Use DEA assumptions for direct air capture

Improve representation of CCS

---

scripts/build_retro_cost.py
scripts/prepare_sector_network.py

small fixes:
- import missing sys package and remove unnecessary import of scipy
- add encoding when reading csv to (soon to be depreciated script version) build retrofitting costs to avoid encoding error

Import sys

---

scripts/build_industrial_energy_demand_per_country_today.py
scripts/build_industrial_production_per_country.py
scripts/build_population_layouts.py
scripts/build_retro_cost.py
scripts/make_summary.py
scripts/plot_network.py
scripts/plot_summary.py
scripts/prepare_sector_network.py

address FutureWarning regarding set operations on pd.Index

---

scripts/prepare_sector_network.py

Add costs for biogas upgrading

---

scripts/build_biomass_potentials.py

Code cleaning and improved inferral of country index rows which was previously hardcoded. No change in functionality.
```py
from pandas.testing import assert_frame_equal
fn = "old_biomass_potentials.csv"
old = pd.read_csv("old_biomass_potentials.csv", index_col=0)
new = pd.read_csv("biomass_potentials.csv", index_col=0)
assert_frame_equal(old, new)
```
[biomass_potentials.csv](https://github.com/PyPSA/pypsa-eur-sec/files/6432260/biomass_potentials.csv)
[old_biomass_potentials.csv](https://github.com/PyPSA/pypsa-eur-sec/files/6432261/old_biomass_potentials.csv)

Revision: build_biomass_potentials

---

scripts/build_industrial_production_per_country_tomorrow.py

Formatting and move into `__main__`
```py
from pandas.testing import assert_frame_equal
fn = "industrial_production_per_country_tomorrow.csv"
old = pd.read_csv("old_" + fn, index_col=0)
new = pd.read_csv(fn, index_col=0)
assert_frame_equal(old, new)
```
[industrial_production_per_country_tomorrow.csv](https://github.com/PyPSA/pypsa-eur-sec/files/6442482/industrial_production_per_country_tomorrow.csv)
[old_industrial_production_per_country_tomorrow.csv](https://github.com/PyPSA/pypsa-eur-sec/files/6442483/old_industrial_production_per_country_tomorrow.csv)

Revision: industry production per country tomorrow

---

scripts/build_industrial_energy_demand_per_node.py

- some cleaning
- move code into `__main__`

Revision: industrial energy demand per node (full)

---

Snakefile
scripts/build_industry_sector_ratios.py

- code refactoring
- move into `__main__`
- modularise with functions
```py
from pandas.testing import assert_frame_equal
path_old = "../pes-old/pypsa-eur-sec/"
path_new = "../pr/pypsa-eur-sec/"
fn = "resources/industry_sector_ratios.csv"
old = pd.read_csv(path_old + fn, index_col=0)
new = pd.read_csv(path_new + fn, index_col=0)
assert_frame_equal(old, new)
```
[industry_sector_ratios.csv](https://github.com/PyPSA/pypsa-eur-sec/files/6461796/industry_sector_ratios.csv)
[old_industry_sector_ratios.csv](https://github.com/PyPSA/pypsa-eur-sec/files/6461797/old_industry_sector_ratios.csv)

Revision: industry sector ratios

---

config.default.yaml
matplotlibrc
scripts/copy_config.py
scripts/make_summary.py
scripts/plot_network.py
scripts/plot_summary.py

- `matplotlibrc` for default style and backend
- remove unused config options
- option to configure geomap colors
- option to configure geomap bounds
- align wind and solar colours with PyPSA-Eur

Revision: minor changes to plotting and summary scripts

---

Snakefile
scripts/add_brownfield.py
scripts/add_existing_baseyear.py

- handle input files in `Snakefile`
- remove unused imports
- cosmetic code-formatting

Revision: myopic code

---

scripts/prepare_sector_network.py

From https://github.com/PyPSA/technology-data/pull/35

Adapt to technology-data changes

---

config.default.yaml
doc/release_notes.rst
scripts/prepare_sector_network.py

Requires updates of `technology-data` repository to include data for `H2 liquefaction` https://github.com/PyPSA/technology-data/pull/32.

add H2 liquefaction cost to H2 shipping demand

---

scripts/copy_config.py

previously name conflict with pypsa-eur-sec config

fix copying pypsa-eur config

---

Snakefile

works for Gurobi, otherwise keeps thread count to 4

solve_network: take threads from solver setting

---

Snakefile
config.default.yaml
doc/data.csv
doc/release_notes.rst
scripts/build_salt_cavern_potentials.py
scripts/prepare_sector_network.py

add regionalised hydrogen salt cavern storage potentials

---

Snakefile
config.default.yaml
doc/release_notes.rst
scripts/retrieve_sector_databundle.py

add option to automatically download and extract sector databundle

---

Snakefile
config.default.yaml
doc/release_notes.rst
scripts/prepare_sector_network.py
scripts/solve_network.py

allow H2 retrofitting from CH4 pipelines without endogenous CH4 grid

---

doc/release_notes.rst
scripts/retrieve_sector_databundle.py

update data bundle

---

scripts/solve_network.py

Fixes issue with specifying /tmp path

---

config.default.yaml
scripts/prepare_sector_network.py

Allow coal power plant with carbon capture.
Carbon capture capital cost is based on the "biomass CHP capture" from the PyPSA/technology-data repository.

Add coal with carbon capture

---

scripts/prepare_sector_network.py

closes #247
introduced: https://github.com/PyPSA/pypsa-eur-sec/commit/95e676828ad087a778399c1921d4b2929ef5c6f3
For PTES this changes CAPEX from 11.43 EUR/kWh to 0.54 EUR/kWh

fix unit conversion for thermal energy storage

---

config.default.yaml
doc/release_notes.rst
scripts/prepare_sector_network.py

Pellet boilers for decentral use
should close #255

Pellet boiler

---

Snakefile

Fix input listing in Snakefile

---

.github/workflows/ci.yaml

The problem before was that it tried to install is via pip

CI: make coincbc and ipopt installed by conda

---

scripts/prepare_sector_network.py

Adresses https://github.com/PyPSA/pypsa-eur/issues/444 for this branch . `solve_network` seems to be working.

[import-trial] Fix: Non-compliant lines for transmission losses.

---

config.default.yaml

This PR should allow different shipping fuel shares depending on the investment period

add shipping shares for different years

---

scripts/add_existing_baseyear.py
scripts/solve_network.py

The myopic code is currently not solving since existing capacities of powerplantmatching for on- and offshore wind a larger than the technical potential at some nodes.
This PR should adjust the maximum potential at one node to the existing capacities if the existing one's are larger.

myopic: adjust p_nom_max if existing larger
