.gitignore, Snakefile, config.default.yaml, config.myopic.yaml, doc/installation.rst, doc/release_notes.rst, scripts/build_ammonia_production.py, scripts/build_industrial_demand.py, scripts/build_industrial_demand_per_country.py, scripts/build_industrial_energy_demand_per_country.py, scripts/build_industrial_energy_demand_per_country_today.py, scripts/build_industrial_production_per_country.py, scripts/build_industrial_production_per_country_tomorrow.py, scripts/build_industry_sector_ratios.py, scripts/prepare_sector_network.py
This makes clearer what the actual demand for steel, cement, chemicals, aluminium etc. in megatonne per year is in the model.
The split between primary and secondary is handled in an intermediary step which takes today's production routes (in industrial_production_per_country.csv in Mt/a) and calculates the ideal 2050 routes (in industrial_production_per_country_tomorrow.csv in Mt/a).
Also now industry_sector_ratios.csv represents the genuine energy demand in MWh per tonne material - there are no tricks for primary/secondary split manipulation anymore (this is taken care of in build_industrial_production_per_country_tomorrow).
Hopefully this is all more transparent.
This PR addresses Issue https://github.com/PyPSA/pypsa-eur-sec/issues/62.
Still to do:
=> Calculate industrial production in Mt/a before calculating corresponding energy demand

config.default.yaml, doc/release_notes.rst, scripts/prepare_sector_network.py
Reasoning: we can also have fossil and biomass liquid hydrocarbons, as well as production from the Fischer-Tropsch process, particularly for simulations before 2050.
In the medium term we need to tidy up how the energy carrier buses are defined, it's currently messy with buses being defined at different places in the code.
=> Change name of liquid hydrocarbon bus from Fischer-Tropsch to oil

scripts/build_energy_totals.py, scripts/prepare_sector_network.py
In the previous version, the main function assigned year=2011 and then called build_co2_totals() with this year. 
Two problems, first, the year 2011 is only used for certain data fetching functions and not as base year for emissions where year=1990 is used instead. I split these two hard-coded value into two variables. Second, build_co2_totals() is not using its argument year at all. I removed it.  
Furthermore, build_energy_totals() is dependent on specific variables being set and I hence added the required function arguments (eurostat, swiss, idees).
=> Make code more readable; remove misleading function arguments and add necessary ones

scripts/build_retro_cost.py
by not looping the .replace() across all columns of the dataframe.
Circumvents: TypeError: Cannot compare types 'ndarray(dtype=float64)' and 'str'
=> retro: fix renaming u_values subsectors and btype

Snakefile, scripts/build_industrial_energy_demand_per_country_today.py
- speed-up from 20 minutes (single-threaded) to 10 seconds on 8 threads!
- complete `snakemake.input`
- move code into `__main__` and modularise with functions
- add progressbar based on `tqdm`
```py
from pandas.testing import assert_frame_equal
fn = "industrial_energy_demand_per_country_today.csv"
old = pd.read_csv("old_" + fn, index_col=0, header=[0,1])
new = pd.read_csv(fn, index_col=0, header=[0,1])
assert_frame_equal(old, new, check_like=True)
```
[industrial_energy_demand_per_country_today.csv](https://github.com/PyPSA/pypsa-eur-sec/files/6452038/industrial_energy_demand_per_country_today.csv)
[old_industrial_energy_demand_per_country_today.csv](https://github.com/PyPSA/pypsa-eur-sec/files/6452040/old_industrial_energy_demand_per_country_today.csv)
=> Revision: build industrial energy demand per country

scripts/build_industrial_production_per_node.py
- minor code cleaning
```py
import geopandas as gpd
import matplotlib.pyplot as plt
plt.style.use('ggplot')
fn = "industrial_production_elec_s_60.csv"
old_df = pd.read_csv("old_" + fn, index_col=0)
new_df = pd.read_csv(fn, index_col=0)
fn_gdf = "regions_onshore_elec_s_60.geojson"
old_gdf = gpd.read_file("old_" + fn_gdf).set_index('name')
new_gdf = gpd.read_file(fn_gdf).set_index('name')
old = pd.concat([old_gdf, old_df], axis=1)
new = pd.concat([new_gdf, new_df], axis=1)
for carrier in old_df.columns:
fig, ax = plt.subplots(1,2, figsize=(20,10))
fig.suptitle(carrier)
old.plot(carrier, ax=ax[0], legend=True, cmap='Reds')
ax[0].set_title('old')
new.plot(carrier, ax=ax[1], legend=True, cmap='Reds')
ax[1].set_title('new')
``` …
=> Revision: industry production per node

Snakefile, config.default.yaml, scripts/build_population_layouts.py
Code cleaning, move code into `__main__`, add multiprocessing for shapes area calculation.
No change in functionality.
Requires `atlite>=v0.2.2`.
```py
import xarray as xr
import matplotlib.pyplot as plt
xr.set_options(display_style='html')
keys_with_vmax = {"total": 1500,
"urban": 1500,
"rural": 200}
for key, vmax in keys_with_vmax.items():
fn = f"old_pop_layout_{key}.nc"
old = xr.open_dataarray(f"old_pop_layout_{key}.nc")
new = xr.open_dataarray(f"pop_layout_{key}.nc")
fig, ax = plt.subplots()    
old.plot(cmap='Blues', vmax=vmax, label='old', ax=ax)
plt.title(f"old {item}")
fig, ax = plt.subplots()
new.plot(cmap='Blues', vmax=vmax, label='new', ax=ax)
plt.title(f"new {item}")
fig, ax = plt.subplots()
(new-old).plot(cmap='Reds', label='new - old', ax=ax)
plt.title(f"new - old {item}") …
```
=> Revision: build population layout

Snakefile, scripts/build_clustered_population_layouts.py, scripts/build_population_layouts.py
depends on #108 
No change in functionality, but move code into `__main__` and make GeoDataframe a  GeoSeries that can be passed to the `clean_invalid_geometries` function without conversion to a `pd.Series`.
```py
import geopandas as gpd
import matplotlib.pyplot as plt
plt.style.use('ggplot')
fn = "pop_layout_elec_s_60.csv"
fn_gdf = "regions_onshore_elec_s_60.geojson"
old = pd.read_csv("old_"+fn, index_col=0)
old_gdf = gpd.read_file("old_"+fn_gdf).set_index('name')
old = old_gdf.join(old)
new = pd.read_csv(fn, index_col=0)
new_gdf = gpd.read_file(fn_gdf).set_index('name')
new = new_gdf.join(new)
for item in ["total", "rural", "urban"]:
fig, ax = plt.subplots(1,2, figsize=(10,5))
fig.suptitle(item)
vmax = 35000
old.plot(item, ax=ax[0], vmax=vmax)
ax[0].set_title('old') …
```
=> Revision: build clustered population layouts

scripts/add_brownfield.py, scripts/add_existing_baseyear.py, scripts/build_ammonia_production.py, scripts/build_biomass_potentials.py, scripts/build_clustered_population_layouts.py, scripts/build_cop_profiles.py, scripts/build_energy_totals.py, scripts/build_heat_demand.py, scripts/build_industrial_distribution_key.py, scripts/build_industrial_energy_demand_per_country_today.py, scripts/build_industrial_energy_demand_per_node.py, scripts/build_industrial_energy_demand_per_node_today.py, scripts/build_industrial_production_per_country.py, scripts/build_industrial_production_per_country_tomorrow.py, scripts/build_industrial_production_per_node.py, scripts/build_industry_sector_ratios.py, scripts/build_population_layouts.py, scripts/build_retro_cost.py, scripts/build_solar_thermal_profiles.py, scripts/build_temperature_profiles.py, scripts/copy_config.py, scripts/helper.py, scripts/make_summary.py, scripts/plot_network.py, scripts/plot_summary.py, scripts/prepare_sector_network.py, scripts/solve_network.py
Using the `mock_snakemake` from `pypsa-eur/_helpers.py` to run scripts outside snakemake reduces maintenance effort because input and output file names do not have to be modified twice. The function is temporarily copied into `scripts/helper.py` because of complex file dependencies.
=> Revision: use `mock_snakemake` from pypsa-eur

scripts/build_biomass_transport_costs.py, scripts/prepare_sector_network.py
Similar to #148 manage the spatial resolution of solid biomass (copperplated or with biomass transport) through a namespace (think: global dictionary).
This allows to easily vary the spatial resolution of biomass in the model without removing components that are added inside the same script.
Currently the option `biomass_transport` triggers both spatial resolution of biomass as well as the transport of biomass. One could split this into two options.
PR against https://github.com/PyPSA/pypsa-eur-sec/tree/biomass-transport
=> Spatial management for solid biomass (transport)

scripts/solve_network.py
All CHPs in pypsa-eur-sec are operating on the backpressure line and this set of extra constraints to ensure working in the operational space of the CHPs is hence not necessary at the moment.
=> Omitting unnecessary constraints on the CHP units

scripts/prepare_sector_network.py
Rooftop-solar generators are missing the lifetime attribute when they are added.
This avoids that they are saved as brownfield capacities installed in a previous timestep when running myopic optimization. 
I.e, they are not captured in the following line
https://github.com/PyPSA/pypsa-eur-sec/blob/5b9f64354fb8cb6a8d9bfca361b5397347309ab3/scripts/add_existing_baseyear.py#L31
=> Add lifetime to solar-rooftop

scripts/prepare_sector_network.py
In the IPCC 6th Assessment Report, carbon budgets are reported from 2020 onwards.
See Table SPM2 in the Summary for Policymakers
https://www.ipcc.ch/report/ar6/wg1/downloads/report/IPCC_AR6_WGI_SPM.pdf 
Before carbon budgets were reported from 2018 onwards. Substracting emissions in 2018 and 2019 is no longer required.
=> fix-build_carbon_budget

config.default.yaml, scripts/add_existing_baseyear.py, scripts/plot_network.py, scripts/prepare_sector_network.py
- add missing color for H2 liquidation to config.default.yaml
- adjust for myopic optimisation selection of assets to new default lifetime and build year
- remove trailiing whitespace in index of electricity load of pypsa-eur network
=> Small fixes

doc/installation.rst
I guessed the conda commands should have been hightlighted as code similar to https://pypsa-eur.readthedocs.io/en/latest/installation.html#install-python-dependencies. In the wget and tar operation there was a ` too much and xvzf was missing a hyphen.
=> Add missing code directive and hyphon in tar operation

Snakefile
Similarly to pypsa-eur, if the config file is not found, we can create it as a copy of `config.default.yaml`. 
The rationale, just as with pypsa-eur, is that makes it easier to include pypsa-eur-sec as a subworkflow in a snakemake workflow. (See https://github.com/PyPSA/pypsa-eur/pull/105.) It's not strictly speaking necessary, but certainly nice to have when using pypsa-eur-sec as a subworkflow.
=> Create config file from default if not found

scripts/prepare_sector_network.py
with @lisazeyen 
instead of #206 
closes #206
=> fix broken prepare_sector_network when running without gas grid

config.default.yaml, doc/release_notes.rst, scripts/solve_network.py
With the "co2_sequestration_limit" implemented as `extra_functionality`, the duals of the GlobalConstraints were not placed in the 'mu' column (duals for co2 limit and line volume limit were no longer available).
This fixes this behaviour and also adds the "co2_sequestration_limit" to the GlobalConstraints dataframe.
Additionally, added configuration options to handle for which components to keep the shadowprices.
=> fix for GlobalConstraints mu with "co2_sequestration_limit"

data/override_component_attrs/generators.csv, data/override_component_attrs/links.csv, data/override_component_attrs/stores.csv, scripts/add_brownfield.py, scripts/add_existing_baseyear.py, scripts/plot_network.py, scripts/prepare_sector_network.py, scripts/solve_network.py
this PR should resolve some conflicts with the latest changes if running the model with myopic foresight, namely:
- adjust functions to work with the new default lifetime np.inf (instead of previous NaN)
- add electricity grid connection costs to renewables solar and onwind, take the right capital costs if solar is splited into rooftop and utility
- general update of the mocksnakemake for testing
- use the `define_spatial` function also for other conventional carriers
- add lifetime for H2 Stores
- enable to run the myopic code with a spatial resolved gas network, which means:
- adding existing components to the right buses ("EU gas" or all buses with carrier gas)
- avoid doubling of the existing gas network in module add_brownfield
- adjusting the retrofitting pipe line constraint to …
=> Myopic fix

Snakefile, scripts/build_population_weighted_energy_totals.py, scripts/build_transport_demand.py, scripts/helper.py, scripts/prepare_sector_network.py
This PR disentangles the `prepare_data()` function in `prepare_sector_network`.
- adds two new rules `build_transport_demand` and `build_population_weighted_energy_totals`
- renames `prepare_data` to `build_heat_demand`
- calls COP data where needed
=> separate rules for transport demand and nodal energy totals

config.default.yaml
the default set of vintage classes specified in config.default.yaml does not account for the new powerplant database with powerplants built until 2027. This causes an error that is hard to spot :(
increasing the upper range of the list solves the problem.
=> fix grouping years list issue caused by newer powerplant database

doc/release_notes.rst, scripts/prepare_sector_network.py
add explicit documentation of the unit of each bus' carrier
this addresses the issue https://github.com/PyPSA/pypsa-eur-sec/issues/134#event-6804897616
Bus [unit]:
- electricity, low voltage [MWh_el]
- home battery, battery, batteries in transport  [MWh_el]
- coal, nuclear and oil  [MWh_th]
- ice in transport [MWh_th]
- buses in heat sector [MWh_th]
- biogas and biomas [MWh_th]
- co2 atmosphere, co2 stored, process emissions [t_co2]
- H2, shipping_hydrogen_liquefaction [MWh_LHV]
- gas for industry [MWh_LHV]
=> Document units of bus carriers

scripts/add_brownfield.py, scripts/add_existing_baseyear.py, scripts/helper.py, scripts/plot_summary.py, scripts/prepare_sector_network.py, scripts/solve_network.py
This PR generalises tweaking config parameters through the `{sector_opts}` wildcard. Closes #244.
For example `CF+sector+district_heating+potential+0.8` or `CF+sector+v2g+false` will overwrite `snakemake.config` with the following:
```yaml
sector:
district_heating:
potential: 0.8
v2g: false
```
The routine is triggered by a `CF+`. Then you can pipe to any config setting. Just be aware that this will only have an effect on rules with the `{sector_opts}` wildcard.
- Uses `snakemake.utils.update_config`
- This will work even better with #250 because then the update of `snakemake.config` in each rule can be skipped.
=> option to specify any config through sector opts with CF:<label>:<value>

Snakefile, config.default.yaml, scripts/add_existing_baseyear.py, scripts/build_energy_totals.py, scripts/plot_summary.py, scripts/prepare_sector_network.py
This PR should fix three bugs 
1. the option to limit the CO2 emissions by e.g. `cb40ex0` as a sector_opts was not working anymore due to changes in the `build_energy_totals.py script`
2. by changing the` grouping_years` in this PR here #240 to `[1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2020, 2025, 2030]` two issues arise in the `add_existing_baseyear.py `script: 
- components with same names where added to the network (e.g. for planning horizon 2020 existing infrastructure for solar was added with the same name as the extendable assets for this planning horizon)
- the existing heating infrastructure data is not taken from the powerplant matching and should be  therefore evenly distributed over the last 25 years (old grouping_years, not including future years 2025 and 2030)
3. …
=> Fix bug myopic co2

doc/release_notes.rst, scripts/prepare_sector_network.py
This PR should add two more options to aggregate the network temporally:
(1) aggregate timeseries to representative snapshots with e.g. `25sn` as `sector_opts` would results in taking every 25th snapshot
(2) using segmentation method from tsam similar to PyPSA-Eur, except that all time-dependent data is considered (to include e.g. also the COP of heat pumps) and that the options is added to overwrite the pypsa time-series with time profiles generated by tsam. For example `60SEG` in `sector_opts` would results in 60 representative snapshots of the original timeseries.
=> Add more options for temporal aggregation

config.default.yaml, scripts/solve_network.py
The in the `config.yaml` described way to modify the sequestration potential of the CO2 is currently not working correctly. In this PR the description in the `config.yaml` as well as the setting of the constraint in `solve_network.py` are updated.
The CO2 sequestration potential can now be set in the `sector_opts` with e.g. `seq2` to multiply the assumed CO2 storage potential by 2 or `seq0p5` to multiply the assumed CO2 storage potential by 0.5
=> update sector opt for co2 seq potential

Snakefile
Somehow the export is empty if called from within `snakemake`.
If someone wants to investigate...
=> Snakefile: export conda environment

config.default.yaml, doc/release_notes.rst
... rather than liquefied hydrogen.
The problem was also that hydrogen demand for shipping was not well spatially resolved, but despite the lack of data drove the hydrogen infrastructure demand.
Oil for shipping (FT or methanol) is not spatially resolved.
Future improvement: endogenous fuel choice between Fischer-Tropsch, fossil oil, methanol, ammonia, liq. hydrogen.
=> Change default of shipping demand to oil

config.default.yaml, scripts/solve_network.py
=> [import benefits] [DNMY] Import trial transmission losses

scripts/add_existing_baseyear.py
Currently when the brownfield fleet is added to the network VOM (marginal cost) for renewables are taken from the technology-data. In PyPSA-Eur we do not assume any VOM for onshore wind. This results in an inconsistency, existing wind farms get VOM assigned while new ones do not have any. I would suggest to assume the same VOM as in PyPSA-Eur for the existing fleet.
=> take VOM for RES from existing

.github/workflows/ci.yaml, Snakefile, config.default.yaml, doc/installation.rst, test/config.myopic.yaml, test/config.overnight.yaml
Phase out the need to clone technology-data repository in a parallel directory.
This solution directly retrieves the cost data from Github and is analogous to PyPSA-Eur.
=> automatically retrieve technology-data, no git clone

config.default.yaml, doc/release_notes.rst, scripts/prepare_sector_network.py
We already have options for waste heat recovery in FT and H2-CHP. This PR adds electrolysis to the list.
=> add option to use electrolysis waste heat in district heating

scripts/build_energy_totals.py, scripts/build_industrial_production_per_country.py, scripts/build_industry_sector_ratios.py, scripts/helper.py
As I was parsing the text in the ubuntu terminal, there are verbose output that is unnecessary in the snakemake process. Such text such as Ind_Summary, CHI, CHI_emi, CHI_fec, CHI_ued... when a JRC-IDEES-2015_Industry file is open or worked with.
To hide this, I added def mute() in the helper.py and run those in the following script:
- build_industry_sector_ratios.py
- build_industrial_production_per_country.py
- build_energy_totals.py
All in all this is just an output cleanliness issue.
=> Hide uninformative text caused by subprocess outputs

scripts/build_biomass_potentials.py, scripts/build_gas_input_locations.py, scripts/build_population_layouts.py
Fixing some warnings in build_biomass_potentials.py, build_gas_input_locations.py, scripts and build_population_layouts.py'
The warning in build_biomass_potentials.py: `FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.`
The warning in build_gas_input_locations: `SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame.`
The info in build_population_layouts: `The order of elements in grid_cells changed. Check the output of your workflow for correctness.`
=> Fixing some warnings in biomass_potentials, gas_input_locations and population_layouts

config.default.yaml
Add highs solver options to the config. They probably can be fine tuned, I have tested them only with a low temporal resolution (120 time steps).
Solver settings for highs can be find [here](https://ergo-code.github.io/HiGHS/options/definitions.html#solver)
=> add highs solver options

scripts/add_brownfield.py, scripts/add_existing_baseyear.py, scripts/build_energy_totals.py, scripts/build_industrial_distribution_key.py, scripts/build_industrial_production_per_country.py, scripts/build_population_layouts.py, scripts/make_summary.py, scripts/plot_network.py, scripts/plot_summary.py, scripts/prepare_sector_network.py
There are 30 print statement in pypsa-eur-sec. All of them are replaced with logging function. The justification of its level is as below:
- describing the function brownfield is running -> logger.debug
- describing the file with the new planning horizon to be used -> logger.info 
- both are just describing an function that is going to run -> logger.debug
- all that is inside a loop function -> logger.debug
- missing data that is replaced with mean -> logger.info
- The logger are only activated if an missing industrial site is found -> logger.debug
- if its still missing -> logger.warning
- only informing which country have no ammonia demand -> logger.info
- the urbanization rate of each country -> logger.debug
- `print(load * n.buses_t.marginal_price[buses])` result in large tables -> …
=> Replacing print statement with logging
